website:
  build: .
  ports:
    - 7766:80
  volumes:
    - ./dist:/app
  environment:
    PORT: 80
    MONGO_URL: 'mongodb://partio:zpartio2016#@45.55.195.172:27017/partioapp'
  restart: always
  entrypoint: ~/install.sh
